## Numpy
-   https://numpy.org - is an external library
-   numpy is used for **numerical** operations and analysis
-   It is very fast compared to the built-in Python functions
-   Numpy operations are **only on Array** (called ndarray - n dimension array)

In [ ]:
# Installing numpy
! pip install numpy

In [ ]:
import numpy as np
import sys
from datetime import datetime

In [ ]:
# Check speed summing 10000000 numbers using Python's built-in sum function
import numpy as np
import sys
from datetime import datetime

L = range(1000000)

sys.getsizeof(L) * len(L)  # This will give the size of the list in bytes
print("Size of list L in bytes: ", sys.getsizeof(L) * len(L))

start = datetime.now()
%timeit sum_val = sum(L)
delta = datetime.now() - start
print("Sum using Python's built-in sum function took: ", delta)

In [ ]:
# Check speed summing 10000000 numbers using numpy's sum function
import numpy as np
import sys
from datetime import datetime

L = np.arange(1000000)

print("Size of numpy array L in bytes: ", L.itemsize * L.size)

start = datetime.now()
%timeit sum_val = np.sum(L)
delta = datetime.now() - start
print("Sum using numpy's sum function took: ", delta)

In [ ]:
arr = np.array([1, 2, 3, 4, 5]) # In an array, all elements must be of the same type
print(type(arr) )
print(arr.ndim)

In [ ]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]]) # This is a 2D array
print(arr2.shape)  # This will show the shape of the array (number of rows and columns)
print(arr2.ndim)  # This will show the number of dimensions of the array
print(arr2.size)  # This will show the total number of elements in the array
print(arr2.dtype)  # This will show the data type of the array
print(arr2.itemsize)  # This will show the size of each element in bytes


In [ ]:
print(arr2[1][2])
print(arr2[1,2])

In [ ]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[11, 21, 31], [41, 51, 61]]]) # This will create a 2D array with float64 data type
print(arr3.shape)
print(arr3.ndim)

### Building Array using nummpy

In [ ]:
## Different ways to create and initialize nummpy array.
import numpy as np

arr = np.zeros([3,3])
print('Array created using zero function')
print(arr)

arr = np.ones([3,3])
print('Array created using one function')
print(arr)

arr = np.empty([3,2])
print('Array created using empty function')
print(arr)

lst = [[1, 2, 3], [4, 5, 6]]
arr = np.array(lst)
print('Array created using list')
print(arr)

arr = np.arange(0, 10, 1)
print('Array created using arange function')
print(arr)

arr = np.linspace(1, 10, 5)
print('Array created using linspace function')
print(arr)

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = arr1
arr3 = arr1.copy()

print(id(arr1))
print(id(arr2))
print(id(arr3))


In [ ]:
# Matrix operations (In matrix both the array dimensions must be same. And dimensions must be Y x Y)

arr1 = np.array([[1, 2], [4, 5]])
arr2 = np.array([[7, 8], [10, 11]])

print(arr1)
print(arr2)

print('Matrix addition')
print(arr1 + arr2)
print('Matrix subtraction')
print(arr1 - arr2)
print('Normal multiplication')
print(arr1 * arr2)
print('Matrix multiplication')
print(arr1.dot(arr2))



In [ ]:
# Nummpy Array - Math Operations
# arr1 = np.arange(0,10,1)
# arr2 = np.arange(6,16,1)
arr1 = np.array([[1, 2], [4, 5]])
arr2 = np.array([[7, 8], [10, 11]])
print(arr1)
print(arr2)

## adding a number to array
print('add 2 to array')
print(arr1 + 2)

## adding 2 arrays of same dimension
print('add 2 arrays of same size / matrix')
print(arr1 + arr2)

## multiplying arrays of same dimension
print('multiply 2 arrays')
print(arr1 * arr2)

## matrix multiplying arrays of same dimension
print('matrix multiple 2 arrays')
print(arr1.dot(arr2))

In [ ]:
# Numpy universal function (it has around 500 functions)
#   Math functions
#   Trigonometry functions
#   floating functions
#   comparision functions
#   bit functions

arr1 = np.array([[1,0],
                 [2,4]])
arr2 = np.array([[1,2],
                 [3,4]])

In [ ]:
print('adding arrays')
print(np.add(arr1, arr2))

print('multiplying arrays')
print(np.multiply(arr1, arr2))

print('lcm arrays')
print(np.lcm(arr1,arr2))
print(np.gcd(arr1,arr2))

print('sin of each element in the array arrays')
print(np.sin(arr1))

print('tan of each element in the array arrays')
print(np.tan(arr1))

print(np.bitwise_and(arr1, arr2))

print('log10 of each element in the array')
print(np.log10(arr2))

#check of all elements in the array is non-zero
print('check if all elements in the array is non-zero')
print(np.all(arr1))
print(np.all(arr2))

print('check if any elements in the array is non-zero')
print(np.any(arr1))
print(np.any(arr2))

arr3 = [2+1j, 3 + 5j, 4, 6, 3+ 1j]

print('check complex and real number')
np.iscomplex(arr3)
np.isreal(arr3)

In [ ]:
# looping multi-dimensional array (this grows with dimension)
for i in range(arr1.shape[0]):
    for j in range(arr1.shape[1]):
        print(arr1[i,j])

print('Avoid nested looping')
# looping into each element in a multipl dimensional array (AVOID NESTED LOOP)
for i in np.nditer(arr1):
    print(i)

In [ ]:
## Reshaping the array
arr4 = np.array([[1,2,3],
                 [4,5,6]])

print('2 x 3 arrray')
print(arr4)

print('Transform it into 3 x 2 array')
print(np.reshape(arr4,(3,2)))

print('Transform it into 6 x 1 array')
print(np.reshape(arr4,(6,1)))

## Flattening an array
print('Flattening the array')
print(arr4.ravel())

## Transposing the array (column to row, row to column)
print('Transposing an array')
print(np.transpose(arr4))
print(arr4.T)

In [ ]:
arr1 = np.array([[1,0,3],
                 [2,4,6]])
arr2 = np.array([[3,5,4],
                 [6,7,8]])

# axis=0 means row-wise
# axis=1 means col-wise

# Concartenating or joining the array
print('concartenating arrays axis-0 wise (row-wise)')
print(np.concatenate((arr1, arr2)))
print(np.concatenate((arr1, arr2), axis=0)) # n x m arrays become 2n x m
print(np.vstack((arr1, arr2))) # samething can be done using vstack

print('concartinating axis-1 or column wise')
print(np.concatenate((arr1, arr2), axis=1)) # n x m arrays become n x 2m
print(np.hstack((arr1, arr2))) # samething can be done using hstack

print('concartinating to form flat array')
print(np.concatenate((arr1, arr2), axis=None)) # Flattening arrays

In [ ]:
# splitting arrays (splits the arrays into equal size)
arr5 = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print('split arrays into 2 equal arrays')
print(np.split(arr5, 2))

In [ ]:
# Save numppy array
import numpy as np

#arr6 = np.arange(10)
arr6 = np.array([[10, 20, 30], [50, 60, 70]])
np.savetxt('file_numpy.csv', arr6, delimiter=',') #saves in float format

In [ ]:
# reading array from file
arr6 = np.genfromtxt('file_numpy.csv', delimiter=',')
print(arr6) #reads float value
print(arr6.astype('int')) #convert into int

[[10. 20. 30.]
 [50. 60. 70.]]
[[10 20 30]
 [50 60 70]]
